schema: "classroom50/repo-config/v1"
classroom: "indprog"
assignment: "i-know-flowchart"
owner:
  username: "SaraAtifi"
  id: 259576017
  accepted_at: "2026-09-06T12:10:52Z"
source:
  owner: "geko-crooms"
  owner_id: 316422449
  repo: "i-know-flowchart"
  branch: "main"
